WORD_LIST = [
    {"word": "ephemeral", "es": "efimero", "it": "effimero", "ja": "hakanai", "de": "fluechtig", "fr": "ephemere", "la": "caducus"},
    {"word": "serendipity", "es": "serendipia", "it": "serendipita", "ja": "ko-un na guuzen", "de": "Gluecksfund", "fr": "serendipite", "la": "felix casus"},
    {"word": "luminous", "es": "luminoso", "it": "luminoso", "ja": "kagayaku", "de": "leuchtend", "fr": "lumineux", "la": "lucidus"},
    {"word": "quixotic", "es": "quijotesco", "it": "donchisciottesco", "ja": "risouteki sugiru", "de": "weltfremd", "fr": "quichottesque", "la": "inanis"},
    {"word": "mellifluous", "es": "melifluo", "it": "mellifluo", "ja": "amai hibiki no", "de": "wohlklingend", "fr": "melliflu", "la": "mellifluus"},
    {"word": "perspicacious", "es": "perspicaz", "it": "perspicace", "ja": "satoi", "de": "scharfsinnig", "fr": "perspicace", "la": "perspicax"},
    {"word": "ebullient", "es": "euforico", "it": "esuberante", "ja": "ikiki to shita", "de": "ueberschaeumend", "fr": "exuberant", "la": "effervescens"},
    {"word": "surreptitious", "es": "subrepticio", "it": "furtivo", "ja": "hisoka na", "de": "heimlich", "fr": "subreptice", "la": "furtivus"},
    {"word": "idyllic", "es": "idilico", "it": "idillico", "ja": "nonbiri to shita", "de": "idyllisch", "fr": "idyllique", "la": "rusticus"},
    {"word": "veracious", "es": "veraz", "it": "veritiero", "ja": "shojiki na", "de": "wahrhaftig", "fr": "verace", "la": "verax"},
    {"word": "eloquent", "es": "elocuente", "it": "eloquente", "ja": "yuuben na", "de": "beredt", "fr": "eloquent", "la": "eloquens"},
    {"word": "fortuitous", "es": "fortuito", "it": "fortuito", "ja": "guuzen no", "de": "zufaellig", "fr": "fortuit", "la": "fortuitus"},
    {"word": "ineffable", "es": "inefable", "it": "ineffabile", "ja": "iigatai", "de": "unsagbar", "fr": "ineffable", "la": "ineffabilis"},
    {"word": "penultimate", "es": "penultimo", "it": "penultimo", "ja": "saigo kara futatsu me", "de": "vorletzte", "fr": "avant-dernier", "la": "paenultimus"},
    {"word": "sanguine", "es": "optimista", "it": "sanguigno", "ja": "rakkan teki na", "de": "optimistisch", "fr": "sanguin", "la": "sanguineus"},
    {"word": "vivacious", "es": "vivaz", "it": "vivace", "ja": "katsuryoku aru", "de": "lebhaft", "fr": "plein de vie", "la": "vivax"},
    {"word": "tenacious", "es": "tenaz", "it": "tenace", "ja": "shitsuyou na", "de": "hartnaeckig", "fr": "tenace", "la": "tenax"},
    {"word": "ubiquitous", "es": "ubicuo", "it": "onnipresente", "ja": "doko ni demo iru", "de": "allgegenwaertig", "fr": "omniprésent", "la": "ubique"},
    {"word": "paradox", "es": "paradoja", "it": "paradosso", "ja": "mujun", "de": "Paradox", "fr": "paradoxe", "la": "paradoxon"},
    {"word": "nostalgia", "es": "nostalgia", "it": "nostalgia", "ja": "natsukashisa", "de": "Nostalgie", "fr": "nostalgie", "la": "nostalgia"},
    {"word": "ethereal", "es": "etereo", "it": "etereo", "ja": "ten no you na", "de": "aetherisch", "fr": "etheree", "la": "aetherius"},
    {"word": "magnanimous", "es": "magnanimo", "it": "magnanimo", "ja": "kandai na", "de": "grossmuetig", "fr": "magnanime", "la": "magnanimus"},
    {"word": "loquacious", "es": "locuaz", "it": "loquace", "ja": "oshaberi na", "de": "redselig", "fr": "loquace", "la": "loquax"},
    {"word": "resilient", "es": "resiliente", "it": "resiliente", "ja": "fukkyu suru", "de": "widerstandsfaehig", "fr": "resilient", "la": "robustus"},
    {"word": "altruistic", "es": "altruista", "it": "altruistico", "ja": "ritateki na", "de": "altruistisch", "fr": "altruiste", "la": "benignus"},
    {"word": "benevolent", "es": "benevolente", "it": "benevolo", "ja": "jihi bukai", "de": "wohlwollend", "fr": "bienveillant", "la": "benevolus"},
    {"word": "candid", "es": "sincero", "it": "schietto", "ja": "sotchoku na", "de": "aufrichtig", "fr": "franc", "la": "candidus"},
    {"word": "diligent", "es": "diligente", "it": "diligente", "ja": "kinben na", "de": "fleissig", "fr": "diligent", "la": "diligens"},
    {"word": "erudite", "es": "erudito", "it": "erudito", "ja": "hakushiki na", "de": "gelehrt", "fr": "erudit", "la": "eruditus"},
    {"word": "fervent", "es": "ferviente", "it": "fervente", "ja": "nesshin na", "de": "gluehend", "fr": "fervent", "la": "fervens"},
    {"word": "gregarious", "es": "gregario", "it": "gregario", "ja": "shakouteki na", "de": "gesellig", "fr": "gregaire", "la": "gregarius"},
    {"word": "humble", "es": "humilde", "it": "umile", "ja": "kenson na", "de": "bescheiden", "fr": "humble", "la": "humilis"},
    {"word": "inquisitive", "es": "curioso", "it": "curioso", "ja": "monozuki na", "de": "neugierig", "fr": "curieux", "la": "curiosus"},
    {"word": "jovial", "es": "jovial", "it": "gioviale", "ja": "yoki na", "de": "froehlich", "fr": "jovial", "la": "iovialis"},
    {"word": "kinetic", "es": "cinetico", "it": "cinetico", "ja": "undou no", "de": "kinetisch", "fr": "cinetique", "la": "cineticus"},
    {"word": "labyrinthine", "es": "laberintico", "it": "labirintico", "ja": "meikyu no you na", "de": "labyrinthisch", "fr": "labyrinthique", "la": "labyrinthicus"},
    {"word": "mercurial", "es": "mercurial", "it": "mutevole", "ja": "kimagure na", "de": "launisch", "fr": "mercuriel", "la": "mercurialis"},
    {"word": "nonchalant", "es": "indiferente", "it": "noncurante", "ja": "heiki na", "de": "gleichgueltig", "fr": "nonchalant", "la": "neglegens"},
    {"word": "opulent", "es": "opulento", "it": "opulento", "ja": "yuutaka na", "de": "uppig", "fr": "opulent", "la": "opulentus"},
    {"word": "poignant", "es": "conmovedor", "it": "commovente", "ja": "kokoro wo utsu", "de": "ergreifend", "fr": "poignant", "la": "acutus"},
    {"word": "querulous", "es": "quejumbroso", "it": "querulo", "ja": "fuhei wo iu", "de": "noergelnd", "fr": "querelleur", "la": "querulus"},
    {"word": "rapturous", "es": "extasiado", "it": "estatico", "ja": "uchouten no", "de": "entrueckt", "fr": "extatique", "la": "raptus"},
    {"word": "sagacious", "es": "sagaz", "it": "sagace", "ja": "kenmei na", "de": "scharfsinnig", "fr": "sagace", "la": "sagax"},
    {"word": "taciturn", "es": "taciturno", "it": "taciturno", "ja": "mukuchi na", "de": "schweigsam", "fr": "taciturne", "la": "taciturnus"},
    {"word": "unctuous", "es": "untuoso", "it": "untuoso", "ja": "obekka no", "de": "schmeichlerisch", "fr": "onctueux", "la": "unctuosus"},
    {"word": "verbose", "es": "verboso", "it": "verboso", "ja": "jouchou na", "de": "weitschweifig", "fr": "verbeux", "la": "verbosus"},
    {"word": "whimsical", "es": "caprichoso", "it": "capriccioso", "ja": "kimagure na", "de": "launenhaft", "fr": "fantaisiste", "la": "levis"},
    {"word": "xenial", "es": "hospitalario", "it": "ospitale", "ja": "kantai no", "de": "gastfreundlich", "fr": "hospitalier", "la": "hospitalis"},
    {"word": "zealous", "es": "entusiasta", "it": "zelante", "ja": "nesshin na", "de": "eifrig", "fr": "zele", "la": "studiosus"},
    {"word": "affable", "es": "afable", "it": "affabile", "ja": "shinshiou no ii", "de": "umgaenglich", "fr": "affable", "la": "affabilis"},
    {"word": "blithe", "es": "alegre", "it": "allegro", "ja": "yoki na", "de": "heiter", "fr": "insouciant", "la": "hilaris"},
    {"word": "clement", "es": "clemente", "it": "clemente", "ja": "onwa na", "de": "milde", "fr": "clement", "la": "clemens"},
    {"word": "dexterous", "es": "diestro", "it": "destro", "ja": "takumi na", "de": "geschickt", "fr": "habile", "la": "dexter"},
    {"word": "effulgent", "es": "refulgente", "it": "fulgente", "ja": "kagayakashii", "de": "strahlend", "fr": "resplendissant", "la": "fulgidus"},
    {"word": "furtive", "es": "furtivo", "it": "furtivo", "ja": "kosokoso shita", "de": "verstohlen", "fr": "furtif", "la": "furtivus"},
    {"word": "garrulous", "es": "garrulo", "it": "garrulo", "ja": "taben na", "de": "geschwaetzig", "fr": "bavard", "la": "garrulus"},
    {"word": "halcyon", "es": "apacible", "it": "sereno", "ja": "heion na", "de": "friedlich", "fr": "serein", "la": "alcyonius"},
    {"word": "imperturbable", "es": "impasible", "it": "imperturbabile", "ja": "heizen jijaku no", "de": "unerschuetterlich", "fr": "imperturbable", "la": "imperturbatus"},
    {"word": "judicious", "es": "juicioso", "it": "giudizioso", "ja": "funbetsu no aru", "de": "besonnen", "fr": "judicieux", "la": "iudiciosus"},
    {"word": "laconic", "es": "laconico", "it": "laconico", "ja": "kanketsu na", "de": "lakonisch", "fr": "laconique", "la": "laconicus"},
    {"word": "melancholy", "es": "melancolia", "it": "malinconia", "ja": "yuutsu", "de": "Melancholie", "fr": "melancolie", "la": "melancholia"},
    {"word": "nefarious", "es": "nefario", "it": "nefario", "ja": "jaaku na", "de": "ruchlos", "fr": "nefaste", "la": "nefarius"},
    {"word": "oblivious", "es": "ajeno", "it": "ignaro", "ja": "ki ga tsukanai", "de": "unbewusst", "fr": "inconscient", "la": "immemor"},
    {"word": "pernicious", "es": "pernicioso", "it": "pernicioso", "ja": "yugai na", "de": "verderblich", "fr": "pernicieux", "la": "perniciosus"},
    {"word": "quiescent", "es": "quiescente", "it": "quiescente", "ja": "seishi shita", "de": "ruhend", "fr": "quiescent", "la": "quiescens"},
    {"word": "reticent", "es": "reticente", "it": "reticente", "ja": "kuchikazu no sukunai", "de": "zurueckhaltend", "fr": "reticent", "la": "reticens"},
    {"word": "stoic", "es": "estoico", "it": "stoico", "ja": "kinkyoku teki na", "de": "stoisch", "fr": "stoique", "la": "stoicus"},
    {"word": "timorous", "es": "timido", "it": "timoroso", "ja": "okubyou na", "de": "furchtsam", "fr": "timoré", "la": "timorosus"},
    {"word": "urbane", "es": "cortes", "it": "urbano", "ja": "seiren sareta", "de": "kultiviert", "fr": "urbain", "la": "urbanus"},
    {"word": "voracious", "es": "voraz", "it": "vorace", "ja": "dongori no", "de": "gefraessig", "fr": "vorace", "la": "vorax"},
    {"word": "wistful", "es": "nostalgico", "it": "malinconico", "ja": "monoomoi ni fukeru", "de": "wehmuetig", "fr": "melancolique", "la": "desiderans"},
    {"word": "acrimony", "es": "acrimonia", "it": "acrimonia", "ja": "shinratsu sa", "de": "Bitterkeit", "fr": "acrimonie", "la": "acrimonia"},
    {"word": "bilious", "es": "bilioso", "it": "bilioso", "ja": "kimutsukashii", "de": "gallig", "fr": "bilieux", "la": "biliosus"},
    {"word": "confound", "es": "confundir", "it": "confondere", "ja": "konwaku saseru", "de": "verwirren", "fr": "confondre", "la": "confundere"},
    {"word": "dauntless", "es": "intrepido", "it": "intrepido", "ja": "ojike zuni", "de": "unerschrocken", "fr": "intrepide", "la": "impavidus"},
    {"word": "effervescent", "es": "efervescente", "it": "effervescente", "ja": "kihatsu sei no aru", "de": "sprudelnd", "fr": "effervescent", "la": "fervescens"},
    {"word": "fastidious", "es": "meticuloso", "it": "meticoloso", "ja": "kicchou men na", "de": "penibel", "fr": "meticuleux", "la": "fastidiosus"},
    {"word": "guileless", "es": "inocente", "it": "ingenuo", "ja": "junshin na", "de": "arglos", "fr": "candide", "la": "sincerus"},
    {"word": "hapless", "es": "desventurado", "it": "sventurato", "ja": "fuun na", "de": "ungluecklich", "fr": "malheureux", "la": "infelix"},
    {"word": "incandescent", "es": "incandescente", "it": "incandescente", "ja": "hakuretsu shita", "de": "gluehend", "fr": "incandescent", "la": "incandescens"},
    {"word": "jocund", "es": "jovial", "it": "giocondo", "ja": "yoki na", "de": "heiter", "fr": "jovial", "la": "iocundus"},
    {"word": "listless", "es": "languid", "it": "languido", "ja": "mukiryoku na", "de": "lustlos", "fr": "languissant", "la": "languidus"},
    {"word": "munificent", "es": "munificente", "it": "munifico", "ja": "kimae no yoi", "de": "freigebig", "fr": "munificent", "la": "munificus"},
    {"word": "obstinate", "es": "obstinado", "it": "ostinato", "ja": "ganko na", "de": "hartnaeckig", "fr": "obstine", "la": "obstinatus"},
    {"word": "pellucid", "es": "transparente", "it": "pellucido", "ja": "toumeina", "de": "klar", "fr": "pellucide", "la": "pellucidus"},
    {"word": "recondite", "es": "reconidito", "it": "recondito", "ja": "nankaina", "de": "obskur", "fr": "abscons", "la": "reconditus"},
    {"word": "solecism", "es": "solecismo", "it": "solecismo", "ja": "goyou", "de": "Soloezismus", "fr": "solecisme", "la": "soloecismus"},
    {"word": "tractable", "es": "tratable", "it": "trattabile", "ja": "atsukaisuyasui", "de": "fugsam", "fr": "docile", "la": "tractabilis"},
    {"word": "uncanny", "es": "inquietante", "it": "inquietante", "ja": "bukimi na", "de": "unheimlich", "fr": "inquietant", "la": "mirandus"},
    {"word": "vehement", "es": "vehemente", "it": "veemente", "ja": "gekiretsu na", "de": "vehement", "fr": "vehement", "la": "vehemens"},
    {"word": "winsome", "es": "encantador", "it": "affascinante", "ja": "miryokuteki na", "de": "gewinnend", "fr": "charmant", "la": "venustus"},
    {"word": "acumen", "es": "perspicacia", "it": "acume", "ja": "dokusatsuryoku", "de": "Scharfsinn", "fr": "perspicacite", "la": "acumen"},
    {"word": "beatitude", "es": "beatitud", "it": "beatitudine", "ja": "shigoku no shiawase", "de": "Seligkeit", "fr": "beatitude", "la": "beatitudo"},
    {"word": "cacophony", "es": "cacofonia", "it": "cacofonia", "ja": "fukyouwa on", "de": "Kakophonie", "fr": "cacophonie", "la": "cacophonia"},
    {"word": "dearth", "es": "escasez", "it": "scarsita", "ja": "fusoku", "de": "Mangel", "fr": "penurie", "la": "inopia"},
    {"word": "effete", "es": "agotado", "it": "esaurito", "ja": "suijaku shita", "de": "erschoepft", "fr": "epuise", "la": "effetus"},
    {"word": "fallacious", "es": "falaz", "it": "fallace", "ja": "gobyuu na", "de": "irrtumlich", "fr": "fallacieux", "la": "fallax"},
    {"word": "grandiloquent", "es": "grandilocuente", "it": "magniloquente", "ja": "ookesa na", "de": "grosssprecherisch", "fr": "grandiloquent", "la": "grandiloquus"},
    {"word": "hegemony", "es": "hegemonia", "it": "egemonia", "ja": "haken", "de": "Hegemonie", "fr": "hegemonie", "la": "hegemonia"},
    {"word": "ignominious", "es": "ignominioso", "it": "ignominioso", "ja": "hazubeki", "de": "schaendlich", "fr": "ignominieux", "la": "ignominiosus"},
    {"word": "jejune", "es": "insipido", "it": "insipido", "ja": "tsumaranai", "de": "fade", "fr": "insipide", "la": "ieiunus"},
    {"word": "kowtow", "es": "someterse", "it": "ossequiare", "ja": "hirefusu", "de": "katzbuckeln", "fr": "se prosterner", "la": "supplicare"},
    {"word": "lugubrious", "es": "lugubre", "it": "lugubre", "ja": "inkina", "de": "duester", "fr": "lugubre", "la": "lugubris"},
    {"word": "maudlin", "es": "lloroso", "it": "piagnucoloso", "ja": "kanjousen ga yoi", "de": "ruehrselig", "fr": "larmoyant", "la": "flebilis"},
    {"word": "nadir", "es": "nadir", "it": "nadir", "ja": "saitei ten", "de": "Tiefpunkt", "fr": "nadir", "la": "imum"},
    {"word": "obtuse", "es": "obtuso", "it": "ottuso", "ja": "nibui", "de": "stumpf", "fr": "obtus", "la": "obtusus"},
    {"word": "parsimony", "es": "parsimonia", "it": "parsimonia", "ja": "kenyaku", "de": "Sparsamkeit", "fr": "parcimonie", "la": "parsimonia"},
    {"word": "quagmire", "es": "pantano", "it": "pantano", "ja": "doronuma", "de": "Morast", "fr": "bourbier", "la": "palus"},
    {"word": "redolent", "es": "fragante", "it": "fragrante", "ja": "kaori takai", "de": "duftend", "fr": "odorant", "la": "redolens"},
    {"word": "sycophant", "es": "sicofante", "it": "adulatore", "ja": "obekka tsukai", "de": "Schmeichler", "fr": "sycophante", "la": "sycophanta"},
    {"word": "temerity", "es": "temeridad", "it": "temerita", "ja": "mubou", "de": "Verwegenheit", "fr": "temerite", "la": "temeritas"},
    {"word": "umbrage", "es": "ofensa", "it": "ombra", "ja": "rippuku", "de": "Anstoss", "fr": "ombrage", "la": "umbra"},
    {"word": "vacillate", "es": "vacilar", "it": "vacillare", "ja": "doyou suru", "de": "schwanken", "fr": "vaciller", "la": "vacillare"},
    {"word": "wanton", "es": "lascivo", "it": "lascivo", "ja": "hoshiimama na", "de": "mutwillig", "fr": "licencieux", "la": "lascivus"},
    {"word": "xenophobia", "es": "xenofobia", "it": "xenofobia", "ja": "gaikokujin girai", "de": "Xenophobie", "fr": "xenophobie", "la": "xenophobia"},
    {"word": "yeoman", "es": "yeoman", "it": "fattore", "ja": "jisaku nou", "de": "Freisasse", "fr": "yeoman", "la": "colonus"},
    {"word": "zenith", "es": "cenit", "it": "zenit", "ja": "tentou", "de": "Zenit", "fr": "zenith", "la": "vertex"},
    {"word": "aberrant", "es": "aberrante", "it": "aberrante", "ja": "ijou na", "de": "abweichend", "fr": "aberrant", "la": "aberrans"},
    {"word": "bucolic", "es": "bucolico", "it": "bucolico", "ja": "denen no", "de": "bukolisch", "fr": "bucolique", "la": "bucolicus"},
    {"word": "corpulent", "es": "corpulento", "it": "corpulento", "ja": "himan shita", "de": "beleibt", "fr": "corpulent", "la": "corpulentus"},
    {"word": "diffident", "es": "timido", "it": "timido", "ja": "jishin no nai", "de": "schuechtern", "fr": "timide", "la": "diffisus"},
    {"word": "equanimity", "es": "ecuanimidad", "it": "equanimita", "ja": "heise i", "de": "Gleichmut", "fr": "equanimite", "la": "aequanimitas"},
    {"word": "felicitous", "es": "feliz", "it": "felice", "ja": "umai", "de": "passend", "fr": "heureux", "la": "felix"},
    {"word": "gaunt", "es": "demacrado", "it": "scarno", "ja": "yase kokeatta", "de": "hager", "fr": "emacie", "la": "macer"},
    {"word": "hubris", "es": "hubris", "it": "hubris", "ja": "gouman", "de": "Hybris", "fr": "hubris", "la": "superbia"},
    {"word": "impetuous", "es": "impetuoso", "it": "impetuoso", "ja": "shoudou teki na", "de": "ungestum", "fr": "impetueux", "la": "impetuosus"},
    {"word": "juxtapose", "es": "yuxtaponer", "it": "giustapporre", "ja": "naraberu", "de": "gegenueberstellen", "fr": "juxtaposer", "la": "iuxtaponere"},
    {"word": "languid", "es": "languido", "it": "languido", "ja": "darui", "de": "traege", "fr": "languide", "la": "languidus"},
    {"word": "melodious", "es": "melodioso", "it": "melodioso", "ja": "utsukushii hibiki no", "de": "wohlklingend", "fr": "melodieux", "la": "melodicus"},
    {"word": "nugatory", "es": "futile", "it": "futile", "ja": "mukachi na", "de": "nichtig", "fr": "futile", "la": "nugatorius"},
    {"word": "opprobrium", "es": "oprobio", "it": "obbrobrio", "ja": "fumeiyo", "de": "Schande", "fr": "opprobre", "la": "opprobrium"},
    {"word": "pejorative", "es": "peyorativo", "it": "peggiorativo", "ja": "keibetsu teki na", "de": "abwertend", "fr": "pejoratif", "la": "deteriorativus"},
    {"word": "rancor", "es": "rencor", "it": "rancore", "ja": "urami", "de": "Groll", "fr": "rancour", "la": "rancor"},
    {"word": "sedulous", "es": "asiduo", "it": "assiduo", "ja": "kinben na", "de": "emsig", "fr": "assidu", "la": "sedulus"},
    {"word": "truculent", "es": "truculento", "it": "truculento", "ja": "koukousen teki na", "de": "aggressiv", "fr": "truculent", "la": "truculentus"},
    {"word": "usurious", "es": "usurero", "it": "usurario", "ja": "kouri kashi no", "de": "wucherisch", "fr": "usuraire", "la": "usurarius"},
    {"word": "vapid", "es": "insipido", "it": "insulso", "ja": "taikutsu na", "de": "geistlos", "fr": "insipide", "la": "vapidus"},
    {"word": "waggish", "es": "bromista", "it": "burlone", "ja": "hyoukin na", "de": "schalkhaft", "fr": "espiegle", "la": "iocosus"},
    {"word": "accolade", "es": "reconocimiento", "it": "riconoscimento", "ja": "sanshou", "de": "Auszeichnung", "fr": "accolade", "la": "laus"},
    {"word": "badinage", "es": "chachara", "it": "ciarla", "ja": "karukuchi", "de": "Neckerei", "fr": "badinage", "la": "iocus"},
    {"word": "callous", "es": "insensible", "it": "insensibile", "ja": "reitan na", "de": "gefuehllos", "fr": "insensible", "la": "callosus"},
    {"word": "debonair", "es": "apuesto", "it": "disinvolto", "ja": "sasso to shita", "de": "charmant", "fr": "debonnaire", "la": "elegans"},
    {"word": "enervate", "es": "enervar", "it": "snervare", "ja": "kiryoku wo yowameru", "de": "entkraeften", "fr": "enerver", "la": "enervare"},
    {"word": "feckless", "es": "inutil", "it": "irresponsabile", "ja": "muryoku na", "de": "nutzlos", "fr": "irresponsable", "la": "inutilis"},
    {"word": "garrulity", "es": "locuacidad", "it": "garullita", "ja": "oshaberi", "de": "Geschwaetzigkeit", "fr": "garrulite", "la": "garrulitas"},
    {"word": "histrionic", "es": "histrionico", "it": "istrionico", "ja": "shibai gakatta", "de": "theatralisch", "fr": "histrionique", "la": "histrionicus"},
    {"word": "inimical", "es": "hostil", "it": "ostile", "ja": "tekitai teki na", "de": "feindlich", "fr": "hostile", "la": "inimicus"},
    {"word": "jettison", "es": "deshacerse", "it": "gettare", "ja": "touki suru", "de": "abwerfen", "fr": "jeter", "la": "iactare"},
    {"word": "kitsch", "es": "kitsch", "it": "kitsch", "ja": "kitchi", "de": "Kitsch", "fr": "kitsch", "la": "vulgaris"},
    {"word": "limpid", "es": "limpido", "it": "limpido", "ja": "sunda", "de": "klar", "fr": "limpide", "la": "limpidus"},
    {"word": "morose", "es": "sombrio", "it": "cupo", "ja": "kimutsukashii", "de": "murrisch", "fr": "morose", "la": "morosus"},
    {"word": "numinous", "es": "numinoso", "it": "numinoso", "ja": "reinai na", "de": "numinos", "fr": "numineux", "la": "numinosus"},
    {"word": "obsequious", "es": "servil", "it": "servile", "ja": "kobihetsurau", "de": "unterwuerfiig", "fr": "obsequieux", "la": "obsequiosus"},
    {"word": "penchant", "es": "inclinacion", "it": "inclinazione", "ja": "keikousei", "de": "Neigung", "fr": "penchant", "la": "inclinatio"},
    {"word": "raconteur", "es": "narrador", "it": "narratore", "ja": "katari te", "de": "Erzaehler", "fr": "raconteur", "la": "narrator"},
    {"word": "sanguinary", "es": "sanguinario", "it": "sanguinario", "ja": "chi namagusakai", "de": "blutruenstig", "fr": "sanguinaire", "la": "sanguinarius"},
    {"word": "tantalize", "es": "atormentar", "it": "tantalizzare", "ja": "jiraseru", "de": "quaelen", "fr": "tantaliser", "la": "torquere"},
    {"word": "unequivocal", "es": "inequivoco", "it": "inequivocabile", "ja": "meihaku na", "de": "eindeutig", "fr": "sans equivoque", "la": "certus"},
    {"word": "venal", "es": "venal", "it": "venale", "ja": "wairo de ugoku", "de": "kaeufllich", "fr": "venal", "la": "venalis"},
    {"word": "wrath", "es": "ira", "it": "ira", "ja": "gekido", "de": "Zorn", "fr": "colere", "la": "ira"},
    {"word": "acerbic", "es": "acerbo", "it": "acerbo", "ja": "shinratsu na", "de": "beissend", "fr": "acerbe", "la": "acerbus"},
    {"word": "baroque", "es": "barroco", "it": "barocco", "ja": "barokku", "de": "barock", "fr": "baroque", "la": "immodicus"},
    {"word": "clandestine", "es": "clandestino", "it": "clandestino", "ja": "himitsu no", "de": "heimlich", "fr": "clandestin", "la": "clandestinus"},
    {"word": "dilettante", "es": "diletante", "it": "dilettante", "ja": "shirouto", "de": "Dilettant", "fr": "dilettante", "la": "amator"},
    {"word": "euphoria", "es": "euforia", "it": "euforia", "ja": "koufuku kan", "de": "Euphorie", "fr": "euphorie", "la": "laetitia"},
    {"word": "flippant", "es": "frivolo", "it": "frivolo", "ja": "keisotsu na", "de": "leichtfertig", "fr": "desinvolte", "la": "levis"},
    {"word": "gratuitous", "es": "gratuito", "it": "gratuito", "ja": "hitsuyou no nai", "de": "unnoetig", "fr": "gratuit", "la": "gratuitus"},
    {"word": "hedonism", "es": "hedonismo", "it": "edonismo", "ja": "kairaku shugi", "de": "Hedonismus", "fr": "hedonisme", "la": "voluptas"},
    {"word": "iconoclast", "es": "iconoclasta", "it": "iconoclasta", "ja": "guuzou hakaisha", "de": "Ikonoklast", "fr": "iconoclaste", "la": "iconoclastes"},
    {"word": "jurisprudence", "es": "jurisprudencia", "it": "giurisprudenza", "ja": "hougaku", "de": "Rechtswissenschaft", "fr": "jurisprudence", "la": "iurisprudentia"},
    {"word": "lachrymose", "es": "lacrimoso", "it": "lacrimoso", "ja": "namida moroi", "de": "weinerlich", "fr": "larmoyant", "la": "lacrimosus"},
    {"word": "mendacious", "es": "mendaz", "it": "mendace", "ja": "uso wo tsuku", "de": "lugnerisch", "fr": "mendacieux", "la": "mendax"},
    {"word": "nonchalance", "es": "indiferencia", "it": "noncuranza", "ja": "mutonjaku", "de": "Gleichgueltigkeit", "fr": "nonchalance", "la": "negligentia"},
    {"word": "ominous", "es": "ominoso", "it": "minaccioso", "ja": "fukitsu na", "de": "unheilverkundend", "fr": "sinistre", "la": "ominosus"},
    {"word": "pedantic", "es": "pedante", "it": "pedante", "ja": "gengaku teki na", "de": "pedantisch", "fr": "pedant", "la": "scholasticus"},
    {"word": "quintessential", "es": "quintaesencial", "it": "quintessenziale", "ja": "tenke i teki na", "de": "wesenhaft", "fr": "quintessentiel", "la": "perfectus"},
    {"word": "reverie", "es": "ensueno", "it": "fantasticheria", "ja": "hakuchuumu", "de": "Traumerei", "fr": "reverie", "la": "somnium"},
    {"word": "soliloquy", "es": "soliloquio", "it": "soliloquio", "ja": "dokuhaku", "de": "Monolog", "fr": "soliloque", "la": "soliloquium"},
    {"word": "travesty", "es": "parodia", "it": "parodia", "ja": "giga ka", "de": "Parodie", "fr": "parodie", "la": "parodia"},
    {"word": "undulate", "es": "ondular", "it": "ondulare", "ja": "nami utsu", "de": "wogen", "fr": "onduler", "la": "undulare"},
    {"word": "veracity", "es": "veracidad", "it": "veridicita", "ja": "seijitsu sa", "de": "Wahrhaftigkeit", "fr": "veracite", "la": "veritas"},
    {"word": "wheedling", "es": "zalamero", "it": "adulatorio", "ja": "odateru", "de": "schmeichelnd", "fr": "cajolant", "la": "blandus"},
    {"word": "acephalous", "es": "acefalo", "it": "acefalo", "ja": "atama no nai", "de": "kopflos", "fr": "acephale", "la": "acephalus"},
    {"word": "bifurcate", "es": "bifurcar", "it": "biforcazione", "ja": "nibun suru", "de": "gabeln", "fr": "bifurquer", "la": "bifurcare"},
    {"word": "caustic", "es": "caustico", "it": "caustico", "ja": "shinratsu na", "de": "aetzend", "fr": "caustique", "la": "causticus"},
    {"word": "decorous", "es": "decoroso", "it": "decoroso", "ja": "reigi tadashii", "de": "anstaendig", "fr": "convenable", "la": "decorus"},
    {"word": "esoteric", "es": "esoterico", "it": "esoterico", "ja": "himitsu shugi no", "de": "esoterisch", "fr": "esoterique", "la": "esotericus"},
    {"word": "fecund", "es": "fecundo", "it": "fecondo", "ja": "hiyoku na", "de": "fruchtbar", "fr": "fecond", "la": "fecundus"},
    {"word": "gestalt", "es": "gestalt", "it": "gestalt", "ja": "zenkei", "de": "Gestalt", "fr": "gestalt", "la": "forma"},
    {"word": "harangue", "es": "arenga", "it": "arringa", "ja": "chouen zetsu", "de": "Tirade", "fr": "harangue", "la": "contio"},
    {"word": "insouciant", "es": "despreocupado", "it": "spensierato", "ja": "nonki na", "de": "unbekuemmert", "fr": "insouciant", "la": "securus"},
    {"word": "lampoon", "es": "libelo", "it": "libello", "ja": "fuushi bun", "de": "Schmaehschrift", "fr": "pamphlet", "la": "libellus"},
    {"word": "malediction", "es": "maldicion", "it": "maledizione", "ja": "noroi", "de": "Fluch", "fr": "malediction", "la": "maledictio"},
    {"word": "nascent", "es": "naciente", "it": "nascente", "ja": "umare tsutsu aru", "de": "entstehend", "fr": "naissant", "la": "nascens"},
    {"word": "oblique", "es": "oblicuo", "it": "obliquo", "ja": "naname no", "de": "schraeg", "fr": "oblique", "la": "obliquus"},
    {"word": "palimpsest", "es": "palimpsesto", "it": "palinsesto", "ja": "youhishi", "de": "Palimpsest", "fr": "palimpseste", "la": "palimpsestus"},
    {"word": "quorum", "es": "quorum", "it": "quorum", "ja": "teisoku suu", "de": "Quorum", "fr": "quorum", "la": "quorum"},
    {"word": "repartee", "es": "replica", "it": "risposta pronta", "ja": "toi soku myou", "de": "Schlagfertigkeit", "fr": "repartie", "la": "promptum"},
    {"word": "sedate", "es": "tranquilo", "it": "sedato", "ja": "ochitsui ta", "de": "gesetzt", "fr": "pose", "la": "sedatus"},
    {"word": "tendentious", "es": "tendencioso", "it": "tendenzioso", "ja": "katayotta", "de": "tendenzios", "fr": "tendancieux", "la": "in partem versans"},
    {"word": "unilateral", "es": "unilateral", "it": "unilaterale", "ja": "ippou teki na", "de": "einseitig", "fr": "unilateral", "la": "unilateralis"},
    {"word": "verisimilitude", "es": "verosimilitud", "it": "verosimiglianza", "ja": "shinjiitsurashisa", "de": "Glaubwuerdigkeit", "fr": "vraisemblance", "la": "verisimilitudo"},
    {"word": "abstruse", "es": "abstruso", "it": "astruso", "ja": "nankai na", "de": "abstrus", "fr": "abstrus", "la": "abstrusus"},
    {"word": "brazen", "es": "descarado", "it": "sfacciato", "ja": "atsukamashii", "de": "dreist", "fr": "effronte", "la": "impudens"},
    {"word": "cogent", "es": "convincente", "it": "cogente", "ja": "settokuryoku no aru", "de": "ueberzeugend", "fr": "convaincant", "la": "cogent"},
    {"word": "deleterious", "es": "deleterio", "it": "deleterio", "ja": "yugai na", "de": "schaedlich", "fr": "deletere", "la": "deleterius"},
    {"word": "exigent", "es": "exigente", "it": "esigente", "ja": "kinkyuu na", "de": "dringend", "fr": "exigeant", "la": "exigens"},
    {"word": "fervid", "es": "fervido", "it": "fervido", "ja": "netsuretsuna", "de": "gluehend", "fr": "fervent", "la": "fervidus"},
    {"word": "glib", "es": "parlanchin", "it": "disinvolto", "ja": "ryu chou sugiru", "de": "glatt", "fr": "facile", "la": "volubilis"},
    {"word": "imbue", "es": "impregnar", "it": "impregnare", "ja": "shimikomi saseru", "de": "durchdringen", "fr": "imprégner", "la": "imbuere"},
    {"word": "jocular", "es": "jocoso", "it": "giocoso", "ja": "joudan zuki na", "de": "scherzhaft", "fr": "jovial", "la": "iocosus"},
    {"word": "knell", "es": "tanido funbre", "it": "rintocco funebre", "ja": "tomurai no kane", "de": "Totengelaeut", "fr": "glas", "la": "campana funebris"},
    {"word": "languor", "es": "languidez", "it": "languore", "ja": "kentai kan", "de": "Traegheit", "fr": "langueur", "la": "languor"},
    {"word": "machination", "es": "maquinacion", "it": "macchinazione", "ja": "inbou", "de": "Machenschaft", "fr": "machination", "la": "machinatio"},
    {"word": "oscillate", "es": "oscilar", "it": "oscillare", "ja": "shindou suru", "de": "schwingen", "fr": "osciller", "la": "oscillare"},
    {"word": "panacea", "es": "panacea", "it": "panacea", "ja": "bannou yaku", "de": "Allheilmittel", "fr": "panacee", "la": "panacea"},
    {"word": "rectitude", "es": "rectitud", "it": "rettitudine", "ja": "seichoku", "de": "Rechtschaffenheit", "fr": "rectitude", "la": "rectitudo"},
    {"word": "soporific", "es": "soporifero", "it": "soporifero", "ja": "nemuke wo moyoosu", "de": "einschlaefrend", "fr": "soporifique", "la": "soporificus"},
    {"word": "turgid", "es": "turgente", "it": "turgido", "ja": "bouchou shita", "de": "geschwollen", "fr": "turgescent", "la": "turgidus"},
    {"word": "usurp", "es": "usurpar", "it": "usurpare", "ja": "ouryou suru", "de": "usurpieren", "fr": "usurper", "la": "usurpare"},
    {"word": "virulent", "es": "virulento", "it": "virulento", "ja": "moudoku no", "de": "virulent", "fr": "virulent", "la": "virulentus"},
    {"word": "cosmopolitan", "es": "cosmopolita", "it": "cosmopolita", "ja": "sekai shimin no", "de": "kosmopolitisch", "fr": "cosmopolite", "la": "cosmopolita"},
    {"word": "yore", "es": "antano", "it": "tempo antico", "ja": "mukashi", "de": "Vorzeit", "fr": "jadis", "la": "olim"},
    {"word": "zephyr", "es": "cefiro", "it": "zefiro", "ja": "soyokaze", "de": "Zephyr", "fr": "zephyr", "la": "zephyrus"},
    {"word": "anathema", "es": "anatema", "it": "anatema", "ja": "noroi", "de": "Anathema", "fr": "anatheme", "la": "anathema"},
    {"word": "bombastic", "es": "bombastico", "it": "ampolloso", "ja": "kodai na", "de": "bombastisch", "fr": "grandiloquent", "la": "inflatus"},
    {"word": "circumspect", "es": "circunspecto", "it": "circospetto", "ja": "shinchoo na", "de": "umsichtig", "fr": "circonspect", "la": "circumspectus"},
    {"word": "duplicity", "es": "duplicidad", "it": "duplicita", "ja": "nimaijita", "de": "Doppelzuengigkeit", "fr": "duplicite", "la": "duplicitas"},
    {"word": "ennui", "es": "tedio", "it": "noia", "ja": "kentai", "de": "Langeweile", "fr": "ennui", "la": "taedium"},
    {"word": "facetious", "es": "gracioso", "it": "faceto", "ja": "karukuchi na", "de": "witzig", "fr": "facetieux", "la": "facetus"},
    {"word": "galvanize", "es": "galvanizar", "it": "galvanizzare", "ja": "katsusei ka suru", "de": "galvanisieren", "fr": "galvaniser", "la": "stimulare"},
    {"word": "harbinger", "es": "precursor", "it": "presagio", "ja": "sakiburee", "de": "Vorbote", "fr": "presage", "la": "praenuntius"},
    {"word": "innuendo", "es": "insinuacion", "it": "insinuazione", "ja": "honomekashi", "de": "Andeutung", "fr": "insinuation", "la": "innuendo"},
    {"word": "kismet", "es": "destino", "it": "destino", "ja": "unmei", "de": "Schicksal", "fr": "destin", "la": "fatum"},
    {"word": "lithe", "es": "agil", "it": "agile", "ja": "shinayaka na", "de": "geschmeidig", "fr": "souple", "la": "agilis"},
    {"word": "mnemonic", "es": "mnemonico", "it": "mnemonico", "ja": "kioku jutsu no", "de": "mnemonisch", "fr": "mnemonique", "la": "mnemonicus"},
    {"word": "nebulous", "es": "nebuloso", "it": "nebuloso", "ja": "bakuzen to shita", "de": "nebulos", "fr": "nebuleux", "la": "nebulosus"},
    {"word": "opaque", "es": "opaco", "it": "opaco", "ja": "futoken no", "de": "undurchsichtig", "fr": "opaque", "la": "opacus"},
    {"word": "pique", "es": "irritacion", "it": "irritazione", "ja": "rippuku", "de": "Veraergerung", "fr": "pique", "la": "offensio"},
    {"word": "replete", "es": "repleto", "it": "pieno", "ja": "michita", "de": "voll", "fr": "repu", "la": "repletus"},
    {"word": "scintillate", "es": "centellear", "it": "scintillare", "ja": "kirameku", "de": "funkeln", "fr": "scintiller", "la": "scintillare"},
    {"word": "torpid", "es": "torpe", "it": "torpido", "ja": "mukiryoku na", "de": "traege", "fr": "torpide", "la": "torpidus"},
    {"word": "unassailable", "es": "inexpugnable", "it": "inattaccabile", "ja": "nankoufu raku no", "de": "unangreifbar", "fr": "inattaquable", "la": "inexpugnabilis"},
    {"word": "visceral", "es": "visceral", "it": "viscerale", "ja": "naizou no", "de": "viszeral", "fr": "visceral", "la": "visceralis"},
    {"word": "wary", "es": "cauteloso", "it": "cauto", "ja": "keikaishita", "de": "vorsichtig", "fr": "prudent", "la": "cautus"},
    {"word": "acrid", "es": "acre", "it": "acre", "ja": "shigeki teki na", "de": "scharf", "fr": "acre", "la": "acer"},
    {"word": "bluster", "es": "fanfarronear", "it": "vantarsi", "ja": "wameku", "de": "prahlen", "fr": "fanfaronner", "la": "iactare"},
    {"word": "compunction", "es": "remordimiento", "it": "rimorso", "ja": "ryoushin no kashaku", "de": "Gewissensbisse", "fr": "remords", "la": "compunctio"},
    {"word": "dalliance", "es": "coqueteo", "it": "civetteria", "ja": "ichatsuki", "de": "Flirt", "fr": "badinage", "la": "lusus"},
    {"word": "enigmatic", "es": "enigmatico", "it": "enigmatico", "ja": "nazo meit ta", "de": "raetselhaft", "fr": "enigmatique", "la": "enigmaticus"},
    {"word": "flabbergast", "es": "asombrar", "it": "sbalordire", "ja": "azen to saseru", "de": "verbluffen", "fr": "abasourdir", "la": "obstupefacere"},
    {"word": "gallant", "es": "galante", "it": "galante", "ja": "yuukan na", "de": "galant", "fr": "galant", "la": "gallans"},
    {"word": "harrow", "es": "angustiar", "it": "angosciare", "ja": "kurushimeru", "de": "quaelen", "fr": "tourmenter", "la": "torquere"},
    {"word": "intrepid", "es": "intrepido", "it": "intrepido", "ja": "yuukan na", "de": "unerschrocken", "fr": "intrepide", "la": "intrepidus"},
    {"word": "jubilant", "es": "jubiloso", "it": "esultante", "ja": "kanki suru", "de": "freudig", "fr": "jubilant", "la": "jubilans"},
    {"word": "ken", "es": "conocimiento", "it": "conoscenza", "ja": "chishiki han'i", "de": "Kenntnisstand", "fr": "portee", "la": "scientia"},
    {"word": "luminary", "es": "luminaria", "it": "luminare", "ja": "chomeijin", "de": "Leuchte", "fr": "sommite", "la": "luminare"},
    {"word": "myopic", "es": "miope", "it": "miope", "ja": "kinshi ganno", "de": "kurzsichtig", "fr": "myope", "la": "myops"},
    {"word": "nettlesome", "es": "irritante", "it": "irritante", "ja": "haradatashii", "de": "aergerlich", "fr": "irritant", "la": "molestus"},
    {"word": "overwrought", "es": "sobreexcitado", "it": "sovreccitato", "ja": "kounshita", "de": "ueber reizt", "fr": "surexcite", "la": "perturbatus"},
    {"word": "placid", "es": "placido", "it": "placido", "ja": "odayaka na", "de": "ruhig", "fr": "placide", "la": "placidus"},
    {"word": "quintessence", "es": "quintaesencia", "it": "quintessenza", "ja": "shinzui", "de": "Quintessenz", "fr": "quintessence", "la": "quinta essentia"},
    {"word": "rancorous", "es": "rencoroso", "it": "rancoroso", "ja": "urami gamashii", "de": "nachtragend", "fr": "rancunier", "la": "rancidus"},
    {"word": "sallow", "es": "cetrino", "it": "giallastro", "ja": "aojiroi", "de": "fahl", "fr": "blafard", "la": "pallidus"},
    {"word": "trenchant", "es": "incisivo", "it": "tagliente", "ja": "surudoi", "de": "treffend", "fr": "tranchant", "la": "acutus"},
    {"word": "unflinching", "es": "firme", "it": "fermo", "ja": "danko toshita", "de": "unerschuetterlich", "fr": "impassible", "la": "immotus"},
    {"word": "venerable", "es": "venerable", "it": "venerabile", "ja": "sonkeisu beki", "de": "ehrwuerdig", "fr": "venerable", "la": "venerabilis"},
    {"word": "beguile", "es": "seducir", "it": "sedurre", "ja": "miwarku suru", "de": "verfuehren", "fr": "seduire", "la": "decipere"},
    {"word": "cogitate", "es": "cogitar", "it": "cogitare", "ja": "jukkou suru", "de": "nachdenken", "fr": "cogiter", "la": "cogitare"},
    {"word": "denouement", "es": "desenlace", "it": "epilogo", "ja": "ketsumatsu", "de": "Auflosung", "fr": "denouement", "la": "exitus"},
    {"word": "epicurean", "es": "epicureo", "it": "epicureo", "ja": "kairaku shugi no", "de": "epikureisch", "fr": "epicurien", "la": "epicureus"},
    {"word": "fortitude", "es": "fortaleza", "it": "fortezza", "ja": "fukutsu no seishin", "de": "Standhaftigkeit", "fr": "fortitude", "la": "fortitudo"},
    {"word": "guileful", "es": "astuto", "it": "astuto", "ja": "koukatsu na", "de": "hinterlistig", "fr": "ruse", "la": "dolosus"},
    {"word": "hauteur", "es": "altivez", "it": "alterigia", "ja": "gouman", "de": "Hochmut", "fr": "hauteur", "la": "superbia"},
    {"word": "inimitable", "es": "inimitable", "it": "inimitabile", "ja": "hiruinai", "de": "unnachahmlich", "fr": "inimitable", "la": "inimitabilis"},
    {"word": "jaded", "es": "hastiado", "it": "annoiato", "ja": "unzari shita", "de": "abgestumpft", "fr": "blase", "la": "satiatus"},
    {"word": "laborious", "es": "laborioso", "it": "laborioso", "ja": "hone no oreru", "de": "muhsam", "fr": "laborieux", "la": "laboriosus"},
    {"word": "motley", "es": "abigarrado", "it": "eterogeneo", "ja": "madara moyo no", "de": "bunt gemischt", "fr": "bigarre", "la": "varius"},
    {"word": "nullify", "es": "anular", "it": "annullare", "ja": "mukou ni suru", "de": "nichtig machen", "fr": "annuler", "la": "irritum facere"},
    {"word": "obdurate", "es": "obstinado", "it": "ostinato", "ja": "ganko na", "de": "hartnaeckig", "fr": "obstine", "la": "obduratus"},
    {"word": "penurious", "es": "mezquino", "it": "meschino", "ja": "binbou na", "de": "karg", "fr": "chiche", "la": "parcus"},
    {"word": "quotidian", "es": "cotidiano", "it": "quotidiano", "ja": "nichijou no", "de": "alltaeglich", "fr": "quotidien", "la": "quotidianus"},
    {"word": "remonstrate", "es": "protestar", "it": "protestare", "ja": "kogi suru", "de": "Einwaende erheben", "fr": "remonter", "la": "remonstrare"},
    {"word": "salacious", "es": "salaz", "it": "salace", "ja": "koushoku na", "de": "lustern", "fr": "salace", "la": "salax"},
    {"word": "transgress", "es": "transgredir", "it": "trasgredire", "ja": "ihan suru", "de": "ubertreten", "fr": "transgresser", "la": "transgredi"},
    {"word": "ungainly", "es": "torpe", "it": "goffo", "ja": "bukakkou na", "de": "unbeholfen", "fr": "gauche", "la": "inhabilis"},
    {"word": "vacuous", "es": "vacuo", "it": "vacuo", "ja": "kuukyo na", "de": "leer", "fr": "vide", "la": "vacuus"},
    {"word": "weal", "es": "bienestar", "it": "benessere", "ja": "koufuku", "de": "Wohlstand", "fr": "bien-etre", "la": "bonum"},
    {"word": "ablution", "es": "ablucion", "it": "abluzione", "ja": "mokuyoku", "de": "Waschung", "fr": "ablution", "la": "ablutio"},
    {"word": "boorish", "es": "grosero", "it": "rozzo", "ja": "soya na", "de": "toelpelhaft", "fr": "grossier", "la": "agrestis"},
    {"word": "caprice", "es": "capricho", "it": "capriccio", "ja": "kimagure", "de": "Laune", "fr": "caprice", "la": "libido"},
    {"word": "denigrate", "es": "denigrar", "it": "denigrare", "ja": "chuushou suru", "de": "verunglimpfen", "fr": "denigrer", "la": "denigrare"},
    {"word": "emollient", "es": "emoliente", "it": "emolliente", "ja": "nanka zai", "de": "erweichend", "fr": "emollient", "la": "emolliens"},
    {"word": "futile", "es": "futile", "it": "futile", "ja": "muda na", "de": "nutzlos", "fr": "futile", "la": "futilis"},
    {"word": "heretical", "es": "heretico", "it": "eretico", "ja": "itanno", "de": "ketzerisch", "fr": "heretique", "la": "haereticus"},
    {"word": "impotent", "es": "impotente", "it": "impotente", "ja": "muryoku na", "de": "machtlos", "fr": "impuissant", "la": "impotens"},
    {"word": "juxtaposition", "es": "yuxtaposicion", "it": "giustapposizione", "ja": "nanarabi", "de": "Gegenuberstellung", "fr": "juxtaposition", "la": "iuxtapositio"},
    {"word": "lecherous", "es": "lascivo", "it": "lussurioso", "ja": "koushoku na", "de": "wollustig", "fr": "luxurieux", "la": "lascivus"},
    {"word": "moribund", "es": "moribundo", "it": "moribondo", "ja": "hinshin no", "de": "sterbend", "fr": "moribond", "la": "moribundus"},
    {"word": "noxious", "es": "nocivo", "it": "nocivo", "ja": "yugai na", "de": "schaedlich", "fr": "nocif", "la": "noxius"},
    {"word": "obscure", "es": "oscuro", "it": "oscuro", "ja": "aimai na", "de": "unklar", "fr": "obscur", "la": "obscurus"},
    {"word": "penury", "es": "penuria", "it": "penuria", "ja": "gokuhin", "de": "Armut", "fr": "penurie", "la": "penuria"},
    {"word": "raucous", "es": "ruidoso", "it": "rauco", "ja": "sawagashii", "de": "larmend", "fr": "rauque", "la": "raucus"},
    {"word": "seraphic", "es": "serafico", "it": "serafico", "ja": "tenshi no you na", "de": "seraphisch", "fr": "seraphique", "la": "seraphicus"},
    {"word": "torpor", "es": "torpor", "it": "torpore", "ja": "mukankakunasa", "de": "Benommenheit", "fr": "torpeur", "la": "torpor"},
    {"word": "ultimatum", "es": "ultimatum", "it": "ultimatum", "ja": "saigo tsuuchoo", "de": "Ultimatum", "fr": "ultimatum", "la": "ultimatum"},
    {"word": "vicissitude", "es": "vicisitud", "it": "vicissitudine", "ja": "henten", "de": "Wechselfall", "fr": "vicissitude", "la": "vicissitudo"},
    {"word": "abeyance", "es": "suspension", "it": "sospensione", "ja": "ichiji teishi", "de": "Schwebezustand", "fr": "suspension", "la": "suspensio"},
    {"word": "circuitous", "es": "indirecto", "it": "tortuoso", "ja": "mawari michi no", "de": "umstaendlich", "fr": "tortueux", "la": "devius"},
    {"word": "dolorous", "es": "doloroso", "it": "doloroso", "ja": "kanashii", "de": "schmerzhaft", "fr": "douloureux", "la": "dolorosus"},
    {"word": "edify", "es": "edificar", "it": "edificare", "ja": "kyouka suru", "de": "erbauen", "fr": "edifier", "la": "aedificare"},
    {"word": "glower", "es": "mirar ceñudo", "it": "guardare torvo", "ja": "niramu", "de": "finster blicken", "fr": "regarder de travers", "la": "torve tueri"},
    {"word": "heliocentric", "es": "heliocéntrico", "it": "eliocentrico", "ja": "taiyou chuushin no", "de": "heliozentrisch", "fr": "heliocentrique", "la": "heliocentricus"},
    {"word": "juncture", "es": "coyuntura", "it": "congiuntura", "ja": "setugou ten", "de": "Zeitpunkt", "fr": "jonction", "la": "iunctura"},
    {"word": "laceration", "es": "laceracion", "it": "lacerazione", "ja": "resshoo", "de": "Risswunde", "fr": "laceration", "la": "laceratio"},
    {"word": "machiavellian", "es": "maquiavelico", "it": "machiavellico", "ja": "koukatsu na", "de": "machiavellisch", "fr": "machiavélique", "la": "callidus"},
    {"word": "necromancer", "es": "nigromante", "it": "negromante", "ja": "kourei jutsu shi", "de": "Nekromant", "fr": "necromancien", "la": "necromanticus"},
    {"word": "occult", "es": "oculto", "it": "occulto", "ja": "shinpi teki na", "de": "okkult", "fr": "occulte", "la": "occultus"},
    {"word": "perennial", "es": "perenne", "it": "perenne", "ja": "eikyuu teki na", "de": "ausdauernd", "fr": "perenne", "la": "perennis"},
    {"word": "recalcitrant", "es": "recalcitrante", "it": "recalcitrante", "ja": "hankou teki na", "de": "widerspenstig", "fr": "recalcitrant", "la": "contumax"},
    {"word": "skulduggery", "es": "trampa", "it": "inganno", "ja": "sagi", "de": "Schurkerei", "fr": "fourberie", "la": "fraus"},
    {"word": "transient", "es": "transitorio", "it": "transitorio", "ja": "ichiji teki na", "de": "voruebergehend", "fr": "transitoire", "la": "transiens"},
    {"word": "unfathomable", "es": "insondable", "it": "insondabile", "ja": "hakarishirenai", "de": "unergruendlich", "fr": "insondable", "la": "inscrutabilis"},
    {"word": "vitriol", "es": "vitriolo", "it": "vetriolo", "ja": "shinratsu na kotoba", "de": "Vitriol", "fr": "vitriol", "la": "vitriolum"},
    {"word": "aberration", "es": "aberracion", "it": "aberrazione", "ja": "ijou", "de": "Abweichung", "fr": "aberration", "la": "aberratio"},
    {"word": "brusque", "es": "brusco", "it": "brusco", "ja": "bukkirabou na", "de": "schroff", "fr": "brusque", "la": "asper"},
    {"word": "cognizant", "es": "consciente", "it": "consapevole", "ja": "ninshiki shiteiru", "de": "bewusst", "fr": "conscient", "la": "sciens"},
    {"word": "ephemeron", "es": "efimero", "it": "effimero", "ja": "ichinichi mushi", "de": "Eintagsfliege", "fr": "ephemeron", "la": "ephemeron"},
    {"word": "flagrant", "es": "flagrante", "it": "flagrante", "ja": "medamareru", "de": "flagrant", "fr": "flagrant", "la": "flagrans"},
    {"word": "gesticulate", "es": "gesticular", "it": "gesticolare", "ja": "mi buri de shimesu", "de": "gestikulieren", "fr": "gesticuler", "la": "gesticulari"},
    {"word": "homogeneous", "es": "homogeneo", "it": "omogeneo", "ja": "dou shitsu no", "de": "homogen", "fr": "homogene", "la": "homogeneus"},
    {"word": "impeccable", "es": "impecable", "it": "impeccabile", "ja": "moshi bunno nai", "de": "tadellos", "fr": "impeccable", "la": "impeccabilis"},
    {"word": "lackluster", "es": "apagado", "it": "spento", "ja": "seisai no nai", "de": "glanzlos", "fr": "terne", "la": "sordidus"},
    {"word": "melange", "es": "mezcla", "it": "mescolanza", "ja": "kongoubutsu", "de": "Mischung", "fr": "melange", "la": "mixtura"},
    {"word": "nomadic", "es": "nomada", "it": "nomade", "ja": "yuuboku no", "de": "nomadisch", "fr": "nomade", "la": "vagabundus"},
    {"word": "obfuscate", "es": "ofuscar", "it": "offuscare", "ja": "aimai ni suru", "de": "verschleiern", "fr": "obscurcir", "la": "obscurare"},
    {"word": "phlegmatic", "es": "flematico", "it": "flemmatico", "ja": "reiseina", "de": "phlegmatisch", "fr": "flegmatique", "la": "phlegmaticus"},
    {"word": "quell", "es": "suprimir", "it": "sopprimere", "ja": "shizumeru", "de": "unterdruecken", "fr": "reprimer", "la": "reprimere"},
    {"word": "redoubtable", "es": "temible", "it": "formidabile", "ja": "osoru beki", "de": "respekteinflossend", "fr": "redoutable", "la": "formidabilis"},
    {"word": "sardonic", "es": "sardonico", "it": "sardonico", "ja": "reishou teki na", "de": "sardonisch", "fr": "sardonique", "la": "sardonius"},
    {"word": "tempestuous", "es": "tempestuoso", "it": "tempestoso", "ja": "arashi no you na", "de": "stuermisch", "fr": "tempétueux", "la": "tempestuosus"},
    {"word": "untoward", "es": "inconveniente", "it": "sconveniente", "ja": "futsugou na", "de": "ungelegen", "fr": "facheux", "la": "incommodus"},
    {"word": "vexatious", "es": "vejatorio", "it": "vessatorio", "ja": "haradatashii", "de": "aergerlich", "fr": "vexatoire", "la": "vexans"},
    {"word": "wane", "es": "menguar", "it": "calare", "ja": "otoroeru", "de": "abnehmen", "fr": "decliner", "la": "decrescere"},
    {"word": "blandish", "es": "adular", "it": "adulare", "ja": "odateru", "de": "schmeicheln", "fr": "flatter", "la": "blandiri"},
    {"word": "cataclysm", "es": "cataclismo", "it": "cataclisma", "ja": "daisaigai", "de": "Katastrophe", "fr": "cataclysme", "la": "cataclysmos"},
    {"word": "dissonance", "es": "disonancia", "it": "dissonanza", "ja": "fukyouwa", "de": "Dissonanz", "fr": "dissonance", "la": "dissonantia"},
    {"word": "evanescent", "es": "evanescente", "it": "evanescente", "ja": "kiete yuku", "de": "fluechtig", "fr": "evanescent", "la": "evanescens"},
    {"word": "filigree", "es": "filigrana", "it": "filigrana", "ja": "sen zaiku", "de": "Filigran", "fr": "filigrane", "la": "filum aureum"},
    {"word": "grandeur", "es": "grandeza", "it": "grandiosita", "ja": "soudai sa", "de": "Pracht", "fr": "grandeur", "la": "magnificentia"},
    {"word": "inchoate", "es": "incipiente", "it": "incipiente", "ja": "hajimari no", "de": "unentwickelt", "fr": "embryonnaire", "la": "inchoatus"},
    {"word": "lassitude", "es": "lasitud", "it": "lassitudine", "ja": "kentai kan", "de": "Mattigkeit", "fr": "lassitude", "la": "lassitudo"},
    {"word": "majestic", "es": "majestuoso", "it": "maestoso", "ja": "igi no aru", "de": "majestisch", "fr": "majestueux", "la": "maiestaticus"},
    {"word": "nascence", "es": "nacimiento", "it": "nascita", "ja": "tanjou", "de": "Entstehung", "fr": "naissance", "la": "ortus"},
    {"word": "oeuvre", "es": "obra", "it": "opera", "ja": "sakuhin", "de": "Werk", "fr": "oeuvre", "la": "opus"},
    {"word": "pernickety", "es": "quisquilloso", "it": "pignolo", "ja": "komakai", "de": "pingelig", "fr": "pointilleux", "la": "scrupulosus"},
    {"word": "quandary", "es": "dilema", "it": "dilemma", "ja": "itabasami", "de": "Dilemma", "fr": "dilemme", "la": "dubium"},
    {"word": "solace", "es": "consuelo", "it": "conforto", "ja": "nagusame", "de": "Trost", "fr": "reconfort", "la": "solacium"},
    {"word": "tumultuous", "es": "tumultuoso", "it": "tumultuoso", "ja": "souran no", "de": "stuermisch", "fr": "tumultueux", "la": "tumultuosus"},
    {"word": "vertiginous", "es": "vertiginoso", "it": "vertiginoso", "ja": "me ga mawaru you na", "de": "schwindelerregend", "fr": "vertigineux", "la": "vertiginosus"},
    {"word": "iconography", "es": "iconografia", "it": "iconografia", "ja": "zuzougaku", "de": "Ikonographie", "fr": "iconographie", "la": "iconographia"},
    {"word": "finagle", "es": "enredar", "it": "raggirare", "ja": "gomakasu", "de": "erschleichen", "fr": "rouler", "la": "dolo obtinere"},
    {"word": "impulsive", "es": "impulsivo", "it": "impulsivo", "ja": "shoudouteki na", "de": "impulsiv", "fr": "impulsif", "la": "impulsivus"},
    {"word": "inefficacious", "es": "ineficaz", "it": "inefficace", "ja": "koukanonai", "de": "wirkungslos", "fr": "inefficace", "la": "inefficax"},
    {"word": "alacrity", "es": "presteza", "it": "alacrità", "ja": "kibin sa", "de": "Bereitwilligkeit", "fr": "alacrité", "la": "alacritas"},
]
